# Overview Library:
- Pandas
- Numpy

## Pandas dan Numpy (Overview)



**Pandas**
\
Untuk analisis dan manipulasi data.

Yang akan di bahas:
- CRW (Create, Read, Write)
- Explore Dataframe
- Grouping, Indexing, dan Selecting
- Merging DataFrame
- dll (cari sendiri)

**Numpy**
\
Untuk melakukan operasi numerik yag lebih efisien pada array dan matriks multidimensi.

Library lain yang bergantung pada Numpy:
- Pandas
- Matplotlib
- Scipy

Yang akan di bahas :
- Create Numpy
- Indexing dan Selection
- Numpy Operation dan Function

## Pandas

####**DataFrame (Inisialization)**

In [ ]:
import pandas
import numpy
import plotly.express

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px

In [ ]:
df = pandas.DataFrame()
df = pd.DataFrame()

In [ ]:
first_df = pd.DataFrame(
    {
        'person' : ['mhs a', 'mhs b',],
        'nilai' : [90, 100,],
    }
)

first_df

person  nilai
0  mhs a     90
1  mhs b    100

In [ ]:
sec_df = pd.DataFrame(
    {
        'frien  ds' : ['fadil', 'sapri'],
        'debt' : [100000, 2000]
    },
    index = ['28/09/23', '29/09/03']
)

sec_df

frien  ds    debt
28/09/23     fadil  100000
29/09/03     sapri    2000

#### **Series**
Kumpulan nilai yang memiliki index.
Kita bisa membuat series dari sebuah list

In [ ]:
listmakan = ['nasi goreng', 'kwetiaw', 'mie goreng', 'bihun', 'capcay']
dfseries = pd.Series(listmakan, index = ['sales 1', 'sales 2', 'sales 3', 'sales 4', 'sales 5']);
dfseries


sales 1    nasi goreng
sales 2        kwetiaw
sales 3     mie goreng
sales 4          bihun
sales 5         capcay
dtype: object

In [ ]:
# Cara lain
dfseries_2 = pd.Series(
    ['sabun', 'sampo', 'odol', 'gayung'],
    index = ['bahan 1', 'bahan 2', 'bahan 3', 'bahan 4',]
)

dfseries_2

bahan 1     sabun
bahan 2     sampo
bahan 3      odol
bahan 4    gayung
dtype: object

#### **Reading FIles**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving RTH_Data_2020-2022_preprocessing.csv to RTH_Data_2020-2022_preprocessing.csv


In [ ]:
df = pd.read_csv('Data Preprocessing/RTH_Data_2020-2022_preprocessing.csv')
df

Tahun      Provinsi         Kabupaten/Kota  Luas Wilayah (km2)(A)  \
0     2020          Aceh      Kab. Aceh Selatan                4173.82   
1     2020          Aceh        Kab. Aceh Timur                6041.00   
2     2020          Aceh       Kab. Aceh Tengah                4527.53   
3     2020          Aceh         Kab. Gayo Lues                5549.91   
4     2020          Aceh         Kab. Aceh Jaya                3727.00   
..     ...           ...                    ...                    ...   
790   2022  Maluku Utara  Kota Tidore Kepulauan               13862.86   
791   2022         Papua          Kab. Jayapura               17516.00   
792   2022         Papua       Kab. Biak Numfor               21847.63   
793   2022         Papua          Kota Jayapura                 940.00   
794   2022  Papua Tengah            Kab. Nabire               12075.00   

     Luas RTH (km2)(B)  % RTH(B/A)  Taman Kota (km2)  Hutan Kota (km2)  \
0              0.03697       0.001              0.02              0.00   
1              0.07570       0.001              0.05              0.03   
2              1.11217       0.025              0.32              0.02   
3              0.89272       0.016              0.00              0.89   
4              0.82220       0.022              0.13              0.00   
..                 ...         ...               ...               ...   
790           15.34250       0.111              5.36              9.89   
791            0.03499       0.000              0.00              0.03   
792          680.99590       3.117              0.02              7.60   
793            6.92567       0.737              0.04              6.09   
794            0.08000       0.001              0.00              0.08   

     Jalur hijau di Jalan (km2)  Sempadan Sungai (km2)  Sempadan Pantai (km2)  \
0                          0.00                   0.00                   0.02   
1                          0.00                   0.00                   0.00   
2                          0.02                   0.60                   0.15   
3                          0.00                   0.00                   0.00   
4                          0.11                   0.18                   0.40   
..                          ...                    ...                    ...   
790                        0.07                   0.00                   0.02   
791                        0.00                   0.00                   0.00   
792                        0.88                 667.16                   2.23   
793                        0.05                   0.50                   0.16   
794                        0.00                   0.00                   0.00   

     Tempat Pemakaman Umum (km2)  Sempadan Rel Kereta Api (km2)  \
0                           0.00                            0.0   
1                           0.00                            0.0   
2                           0.01                            0.0   
3                           0.00                            0.0   
4                           0.00                            0.0   
..                           ...                            ...   
790                         0.00                            0.0   
791                         0.00                            0.0   
792                         0.03                            0.0   
793                         0.03                            0.0   
794                         0.00                            0.0   

     Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)  \
0                                                  0.0    
1                                                  0.0    
2                                                  0.0    
3                                                  0.0    
4                                                  0.0    
..                                                 ...    
790                                 

Read format yang lain:
- pd.read_excel()
- dll

[Lihat disini](https://pandas.pydata.org/docs/reference/io.html)

#### DataFrame Explore

In [ ]:
df.shape
#berapa baris dan berapa kolom

(795, 17)

In [ ]:
len(df)

795

In [ ]:
#defaultnya 5, tapi bisa atur sendiri
df.head(2)

Tahun Provinsi     Kabupaten/Kota  Luas Wilayah (km2)(A)  \
0   2020     Aceh  Kab. Aceh Selatan                4173.82   
1   2020     Aceh    Kab. Aceh Timur                6041.00   

   Luas RTH (km2)(B)  % RTH(B/A)  Taman Kota (km2)  Hutan Kota (km2)  \
0            0.03697       0.001              0.02              0.00   
1            0.07570       0.001              0.05              0.03   

   Jalur hijau di Jalan (km2)  Sempadan Sungai (km2)  Sempadan Pantai (km2)  \
0                         0.0                    0.0                   0.02   
1                         0.0                    0.0                   0.00   

   Tempat Pemakaman Umum (km2)  Sempadan Rel Kereta Api (km2)  \
0                          0.0                            0.0   
1                          0.0                            0.0   

   Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)  \
0                                                0.0    
1                                                0.0    

   Pengaman Sumber_Air Baku Mata Air (km2)  Kebun Bibit (km2)  Lain-lain (km2)  
0                                      0.0                0.0              0.0  
1                                      0.0                0.0              0.0

In [ ]:
df.tail(5)

Tahun      Provinsi         Kabupaten/Kota  Luas Wilayah (km2)(A)  \
790   2022  Maluku Utara  Kota Tidore Kepulauan               13862.86   
791   2022         Papua          Kab. Jayapura               17516.00   
792   2022         Papua       Kab. Biak Numfor               21847.63   
793   2022         Papua          Kota Jayapura                 940.00   
794   2022  Papua Tengah            Kab. Nabire               12075.00   

     Luas RTH (km2)(B)  % RTH(B/A)  Taman Kota (km2)  Hutan Kota (km2)  \
790           15.34250       0.111              5.36              9.89   
791            0.03499       0.000              0.00              0.03   
792          680.99590       3.117              0.02              7.60   
793            6.92567       0.737              0.04              6.09   
794            0.08000       0.001              0.00              0.08   

     Jalur hijau di Jalan (km2)  Sempadan Sungai (km2)  Sempadan Pantai (km2)  \
790                        0.07                   0.00                   0.02   
791                        0.00                   0.00                   0.00   
792                        0.88                 667.16                   2.23   
793                        0.05                   0.50                   0.16   
794                        0.00                   0.00                   0.00   

     Tempat Pemakaman Umum (km2)  Sempadan Rel Kereta Api (km2)  \
790                         0.00                            0.0   
791                         0.00                            0.0   
792                         0.03                            0.0   
793                         0.03                            0.0   
794                         0.00                            0.0   

     Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)  \
790                                                0.0    
791                                                0.0    
792                                                0.0    
793                                                0.0    
794                                                0.0    

     Pengaman Sumber_Air Baku Mata Air (km2)  Kebun Bibit (km2)  \
790                                     0.00                0.0   
791                                     0.00                0.0   
792                                     2.85                0.0   
793                                     0.06                0.0   
794                                     0.00                0.0   

     Lain-lain (km2)  
790             0.00  
791             0.00  
792             0.23  
793             0.00  
794             0.00

In [ ]:
# Field Checking
df.columns

Index(['Tahun', 'Provinsi', 'Kabupaten/Kota', 'Luas Wilayah (km2)(A)',
       'Luas RTH (km2)(B)', '% RTH(B/A)', 'Taman Kota (km2)',
       'Hutan Kota (km2)', 'Jalur hijau di Jalan (km2)',
       'Sempadan Sungai (km2)', 'Sempadan Pantai (km2)',
       'Tempat Pemakaman Umum (km2)', 'Sempadan Rel Kereta Api (km2)',
       'Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)',
       'Pengaman Sumber_Air Baku Mata Air (km2)', 'Kebun Bibit (km2)',
       'Lain-lain (km2)'],
      dtype='object')

In [ ]:
# field calling (liat cuman 1 kolom spesifik)
df['Sempadan Pantai (km2)']

0      0.02
1      0.00
2      0.15
3      0.00
4      0.40
       ... 
790    0.02
791    0.00
792    2.23
793    0.16
794    0.00
Name: Sempadan Pantai (km2), Length: 795, dtype: float64

In [ ]:
# Jika mau ke spesifik index
df['Sempadan Pantai (km2)'][4]

0.4

In [ ]:
# Cek Tipe data
df.dtypes

Tahun                                                   int64
Provinsi                                               object
Kabupaten/Kota                                         object
Luas Wilayah (km2)(A)                                 float64
Luas RTH (km2)(B)                                     float64
% RTH(B/A)                                            float64
Taman Kota (km2)                                      float64
Hutan Kota (km2)                                      float64
Jalur hijau di Jalan (km2)                            float64
Sempadan Sungai (km2)                                 float64
Sempadan Pantai (km2)                                 float64
Tempat Pemakaman Umum (km2)                           float64
Sempadan Rel Kereta Api (km2)                         float64
Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)    float64
Pengaman Sumber_Air Baku Mata Air (km2)               float64
Kebun Bibit (km2)                                     float64
Lain-lai

In [ ]:
# Statistika deskriptif
df.describe()

Tahun  Luas Wilayah (km2)(A)  Luas RTH (km2)(B)  % RTH(B/A)  \
count   795.000000           7.950000e+02         795.000000  795.000000   
mean   2021.041509           2.103029e+05          43.469172    4.778006   
std       0.807420           3.444905e+06         130.643507   16.816925   
min    2020.000000           1.810000e+00           0.000000    0.000000   
25%    2020.000000           3.958300e+02           0.087710    0.004000   
50%    2021.000000           1.474020e+03           0.705450    0.057000   
75%    2022.000000           3.851485e+03           8.376950    2.447000   
max    2022.000000           6.737960e+07         787.077550  284.118000   

       Taman Kota (km2)  Hutan Kota (km2)  Jalur hijau di Jalan (km2)  \
count        795.000000        795.000000                  795.000000   
mean           2.223975         14.307283                    2.872579   
std           20.678641         82.909614                   22.761450   
min            0.000000          0.000000                    0.000000   
25%            0.020000          0.000000                    0.000000   
50%            0.070000          0.030000                    0.010000   
75%            0.290000          0.230000                    0.080000   
max          533.350000        781.850000                  313.180000   

       Sempadan Sungai (km2)  Sempadan Pantai (km2)  \
count             795.000000             795.000000   
mean               10.183157               0.994792   
std                62.834117               7.896356   
min                 0.000000               0.000000   
25%                 0.000000               0.000000   
50%                 0.000000               0.000000   
75%                 0.110000               0.000000   
max               689.450000             121.830000   

       Tempat Pemakaman Umum (km2)  Sempadan Rel Kereta Api (km2)  \
count                   795.000000                     795.000000   
mean                      0.543220                       0.039182   
std                       3.144278                       0.231036   
min                       0.000000                       0.000000   
25%                       0.000000                       0.000000   
50%                       0.000000                       0.000000   
75%                       0.130000                       0.000000   
max                      45.450000                       3.590000   

       Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)  \
count                                         795.000000    
mean                                            1.102189    
std                                            26.631994    
min                                             0.000000    
25%                                             0.000000    
50%                                             0.000000    
75%                                             0.000000    
max                                           750.330000    

       Pengaman Sumber_Air Baku Mata Air (km2)  Kebun Bibit (km2)  \
count                               795.000000         795.000000   
mean                                  1.855572           0.290327   
std                                  16.609470           7.090199   
min                                   0.000000           0.000000   
25%                                   0.000000           0.000000   
50%                                   0.000000           0.000000   
75%                                   0.000000           0.000000   
max                                 306.330000         199.270000   

       Lain-lain (km2)  
count       795.000000  
mean          8.399270  
std          49.524855  
min           0.000000  
25%           0.000000  
50%           0.000000  
75%           0.000000  
max         710.920000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 795 entries, 0 to 794
Data columns (total 17 columns):
 #   Column                                              Non-Null Count  Dtype  
---  ------                                              --------------  -----  
 0   Tahun                                               795 non-null    int64  
 1   Provinsi                                            795 non-null    object 
 2   Kabupaten/Kota                                      795 non-null    object 
 3   Luas Wilayah (km2)(A)                               795 non-null    float64
 4   Luas RTH (km2)(B)                                   795 non-null    float64
 5   % RTH(B/A)                                          795 non-null    float64
 6   Taman Kota (km2)                                    795 non-null    float64
 7   Hutan Kota (km2)                                    795 non-null    float64
 8   Jalur hijau di Jalan (km2)                          795 non-null    float64
 9  

In [ ]:
df.count()

Tahun                                                 795
Provinsi                                              795
Kabupaten/Kota                                        795
Luas Wilayah (km2)(A)                                 795
Luas RTH (km2)(B)                                     795
% RTH(B/A)                                            795
Taman Kota (km2)                                      795
Hutan Kota (km2)                                      795
Jalur hijau di Jalan (km2)                            795
Sempadan Sungai (km2)                                 795
Sempadan Pantai (km2)                                 795
Tempat Pemakaman Umum (km2)                           795
Sempadan Rel Kereta Api (km2)                         795
Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)    795
Pengaman Sumber_Air Baku Mata Air (km2)               795
Kebun Bibit (km2)                                     795
Lain-lain (km2)                                       795
dtype: int64

#### **Grouping**

In [ ]:
df.groupby(by = 'Tahun').count()

Provinsi  Kabupaten/Kota  Luas Wilayah (km2)(A)  Luas RTH (km2)(B)  \
Tahun                                                                       
2020        243             243                    243                243   
2021        276             276                    276                276   
2022        276             276                    276                276   

       % RTH(B/A)  Taman Kota (km2)  Hutan Kota (km2)  \
Tahun                                                   
2020          243               243               243   
2021          276               276               276   
2022          276               276               276   

       Jalur hijau di Jalan (km2)  Sempadan Sungai (km2)  \
Tahun                                                      
2020                          243                    243   
2021                          276                    276   
2022                          276                    276   

       Sempadan Pantai (km2)  Tempat Pemakaman Umum (km2)  \
Tahun                                                       
2020                     243                          243   
2021                     276                          276   
2022                     276                          276   

       Sempadan Rel Kereta Api (km2)  \
Tahun                                  
2020                             243   
2021                             276   
2022                             276   

       Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)  \
Tahun                                                       
2020                                                 243    
2021                                                 276    
2022                                                 276    

       Pengaman Sumber_Air Baku Mata Air (km2)  Kebun Bibit (km2)  \
Tahun                                                               
2020                                       243                243   
2021                                       276                276   
2022                                       276                276   

       Lain-lain (km2)  
Tahun                   
2020               243  
2021               276  
2022               276

#### Indexing dan Selecting

In [ ]:
# Untuk row tertentu berdasarkan indexnya saja
df.iloc[1]

Tahun                                                            2020
Provinsi                                                         Aceh
Kabupaten/Kota                                        Kab. Aceh Timur
Luas Wilayah (km2)(A)                                          6041.0
Luas RTH (km2)(B)                                              0.0757
% RTH(B/A)                                                      0.001
Taman Kota (km2)                                                 0.05
Hutan Kota (km2)                                                 0.03
Jalur hijau di Jalan (km2)                                        0.0
Sempadan Sungai (km2)                                             0.0
Sempadan Pantai (km2)                                             0.0
Tempat Pemakaman Umum (km2)                                       0.0
Sempadan Rel Kereta Api (km2)                                     0.0
Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)                0.0
Pengaman Sumber_Air 

In [ ]:
# 0:2 berarti akan mengambil baris dengan index ke 0 sampai 1 (2 baris)
# 3:9 berarti akan mengambil baris dengan index ke 3 sampai 8 (6 baris)
# 3 diakhir adalah kolom
df.iloc[3:9, 2]

3       Kab. Gayo Lues
4       Kab. Aceh Jaya
5    Kab. Bener Meriah
6      Kab. Pidie Jaya
7      Kota Banda Aceh
8          Kota Sabang
Name: Kabupaten/Kota, dtype: object

In [ ]:
# Mengambil index ke 3 sampai 8 dengan semua kolom
df.iloc[3:9, :]

Tahun Provinsi     Kabupaten/Kota  Luas Wilayah (km2)(A)  \
3   2020     Aceh     Kab. Gayo Lues                5549.91   
4   2020     Aceh     Kab. Aceh Jaya                3727.00   
5   2020     Aceh  Kab. Bener Meriah                   1.94   
6   2020     Aceh    Kab. Pidie Jaya                 952.11   
7   2020     Aceh    Kota Banda Aceh                  59.02   
8   2020     Aceh        Kota Sabang                 153.00   

   Luas RTH (km2)(B)  % RTH(B/A)  Taman Kota (km2)  Hutan Kota (km2)  \
3            0.89272       0.016              0.00              0.89   
4            0.82220       0.022              0.13              0.00   
5            0.00200       0.103              0.00              0.00   
6            0.10000       0.011              0.10              0.00   
7            7.09522      12.022              0.93              0.00   
8            0.00754       0.005              0.01              0.00   

   Jalur hijau di Jalan (km2)  Sempadan Sungai (km2)  Sempadan Pantai (km2)  \
3                        0.00                   0.00                   0.00   
4                        0.11                   0.18                   0.40   
5                        0.00                   0.00                   0.00   
6                        0.00                   0.00                   0.00   
7                        0.00                   1.31                   4.85   
8                        0.00                   0.00                   0.00   

   Tempat Pemakaman Umum (km2)  Sempadan Rel Kereta Api (km2)  \
3                          0.0                            0.0   
4                          0.0                            0.0   
5                          0.0                            0.0   
6                          0.0                            0.0   
7                          0.0                            0.0   
8                          0.0                            0.0   

   Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)  \
3                                                0.0    
4                                                0.0    
5                                                0.0    
6                                                0.0    
7                                                0.0    
8                                                0.0    

   Pengaman Sumber_Air Baku Mata Air (km2)  Kebun Bibit (km2)  Lain-lain (km2)  
3                                      0.0                0.0              0.0  
4                                      0.0                0.0              0.0  
5                                      0.0                0.0              0.0  
6                                      0.0                0.0              0.0  
7                                      0.0                0.0              0.0  
8                                      0.0                0.0              0.0

In [ ]:
# untuk kolom sama saja seperti baris
df.iloc[3:9, 3:7]

Luas Wilayah (km2)(A)  Luas RTH (km2)(B)  % RTH(B/A)  Taman Kota (km2)
3                5549.91            0.89272       0.016              0.00
4                3727.00            0.82220       0.022              0.13
5                   1.94            0.00200       0.103              0.00
6                 952.11            0.10000       0.011              0.10
7                  59.02            7.09522      12.022              0.93
8                 153.00            0.00754       0.005              0.01

In [ ]:
# Mau cari index ke 33 di kolom Luas RTH (km2)(B)
df.loc[33, 'Luas RTH (km2)(B)']

2.53656

In [ ]:
# Ngambil sampai index ke 6, untuk kolom tertentu
df.loc[:6, ['Luas RTH (km2)(B)', 'Taman Kota (km2)']]

Luas RTH (km2)(B)  Taman Kota (km2)
0            0.03697              0.02
1            0.07570              0.05
2            1.11217              0.32
3            0.89272              0.00
4            0.82220              0.13
5            0.00200              0.00
6            0.10000              0.10

In [ ]:
# Untuk meng-set menggunakan nama dari isi kolom
df.set_index('Provinsi')

Tahun         Kabupaten/Kota  Luas Wilayah (km2)(A)  \
Provinsi                                                            
Aceh           2020      Kab. Aceh Selatan                4173.82   
Aceh           2020        Kab. Aceh Timur                6041.00   
Aceh           2020       Kab. Aceh Tengah                4527.53   
Aceh           2020         Kab. Gayo Lues                5549.91   
Aceh           2020         Kab. Aceh Jaya                3727.00   
...             ...                    ...                    ...   
Maluku Utara   2022  Kota Tidore Kepulauan               13862.86   
Papua          2022          Kab. Jayapura               17516.00   
Papua          2022       Kab. Biak Numfor               21847.63   
Papua          2022          Kota Jayapura                 940.00   
Papua Tengah   2022            Kab. Nabire               12075.00   

              Luas RTH (km2)(B)  % RTH(B/A)  Taman Kota (km2)  \
Provinsi                                                        
Aceh                    0.03697       0.001              0.02   
Aceh                    0.07570       0.001              0.05   
Aceh                    1.11217       0.025              0.32   
Aceh                    0.89272       0.016              0.00   
Aceh                    0.82220       0.022              0.13   
...                         ...         ...               ...   
Maluku Utara           15.34250       0.111              5.36   
Papua                   0.03499       0.000              0.00   
Papua                 680.99590       3.117              0.02   
Papua                   6.92567       0.737              0.04   
Papua Tengah            0.08000       0.001              0.00   

              Hutan Kota (km2)  Jalur hijau di Jalan (km2)  \
Provinsi                                                     
Aceh                      0.00                        0.00   
Aceh                      0.03                        0.00   
Aceh                      0.02                        0.02   
Aceh                      0.89                        0.00   
Aceh                      0.00                        0.11   
...                        ...                         ...   
Maluku Utara              9.89                        0.07   
Papua                     0.03                        0.00   
Papua                     7.60                        0.88   
Papua                     6.09                        0.05   
Papua Tengah              0.08                        0.00   

              Sempadan Sungai (km2)  Sempadan Pantai (km2)  \
Provinsi                                                     
Aceh                           0.00                   0.02   
Aceh                           0.00                   0.00   
Aceh                           0.60                   0.15   
Aceh                           0.00                   0.00   
Aceh                           0.18                   0.40   
...                             ...                    ...   
Maluku Utara                   0.00                   0.02   
Papua                          0.00                   0.00   
Papua                        667.16                   2.23   
Papua                          0.50                   0.16   
Papua Tengah                   0.00                   0.00   

              Tempat Pemakaman Umum (km2)  Sempadan Rel Kereta Api (km2)  \
Provinsi                                                                   
Aceh                                 0.00                            0.0   
Aceh                                 0.00                            0.0   
Aceh                                 0.01                            0.0   
Aceh                                 0.00                            0.0   
Aceh                                 0.00                            0.0   
...                                   ...                            ...   
Maluku Utara                         0.00       

In [ ]:
# Slicing DataFrame secara Conditional
df['Tahun'] == 2022

0      False
1      False
2      False
3      False
4      False
       ...  
790     True
791     True
792     True
793     True
794     True
Name: Tahun, Length: 795, dtype: bool

In [ ]:
df[
    (df['Taman Kota (km2)'] > 3) & (df['Tahun'] == 2022)
]

Tahun          Provinsi          Kabupaten/Kota  Luas Wilayah (km2)(A)  \
535   2022              Aceh             Kota Langsa                 239.83   
540   2022    Sumatera Utara       Kab. Deli Serdang                2498.00   
569   2022              Riau   Kab. Kuantan Singingi                7656.03   
581   2022  Sumatera Selatan          Kota Palembang                 352.52   
588   2022           Lampung          Kab. Pesawaran                1173.77   
603   2022    Kepulauan Riau     Kota Tanjung Pinang                 144.56   
610   2022        Jawa Barat            Kab. Bandung                1762.00   
637   2022       Jawa Tengah               Kab. Pati                1503.68   
670   2022        Jawa Timur              Kab. Tuban                1839.94   
688   2022              Bali            Kab. Tabanan               83933.00   
689   2022              Bali             Kab. Badung                 418.50   
733   2022  Kalimantan Timur  Kab. Kutai Kartanegara               27263.10   
738   2022  Kalimantan Timur            Kota Bontang                 161.88   
790   2022      Maluku Utara   Kota Tidore Kepulauan               13862.86   

     Luas RTH (km2)(B)  % RTH(B/A)  Taman Kota (km2)  Hutan Kota (km2)  \
535           75.12820      31.326             55.05              0.75   
540          421.45164      16.872             12.89            371.25   
569          624.38840       8.156            533.35             26.98   
581           43.87195      12.445             35.18              0.67   
588           15.49100       1.320             15.49              0.00   
603           25.07202      17.344             20.89              3.91   
610          282.44849      16.030             53.61             12.88   
637          383.57937      25.509             10.40              0.11   
670           35.25125       1.916             25.72              0.06   
688           53.10619       0.063             20.13              0.22   
689          129.91733      31.044            123.63              6.29   
733           77.27856       0.283             76.49              0.21   
738           32.18292      19.881             11.23              0.61   
790           15.34250       0.111              5.36              9.89   

     Jalur hijau di Jalan (km2)  Sempadan Sungai (km2)  Sempadan Pantai (km2)  \
535                       13.51                   5.46                   0.05   
540                        6.34                   0.00                  21.53   
569                        0.08                  12.53                   0.00   
581                        0.81                   0.12                   0.00   
588                        0.00                   0.00                   0.00   
603                        0.04                   0.00                   0.00   
610                      162.06                   1.01                   0.00   
637                        2.13                   5.48                   7.86   
670                        0.00                   0.00                   0.37   
688                        0.00                   0.02                   0.00   
689                        0.00                   0.00                   0.00   
733                        0.06                   0.00                   0.00   
738                        0.05                   0.76                  13.48   
790                        0.07                   0.00                   0.02   

     Tempat Pemakaman Umum (km2)  Sempadan Rel Kereta Api (km2)  \
535                         0.32                           0.00   
540                         9.44                           0.00   
569                         0.84                           0.00   
581                         1.42                           0.10   
588                         0.00                           0.00   
603                         0.23                           0.00   
610                    

In [ ]:
filter = df['% RTH(B/A)'] > 0.1
df.where(filter)

Tahun      Provinsi         Kabupaten/Kota  Luas Wilayah (km2)(A)  \
0       NaN           NaN                    NaN                    NaN   
1       NaN           NaN                    NaN                    NaN   
2       NaN           NaN                    NaN                    NaN   
3       NaN           NaN                    NaN                    NaN   
4       NaN           NaN                    NaN                    NaN   
..      ...           ...                    ...                    ...   
790  2022.0  Maluku Utara  Kota Tidore Kepulauan               13862.86   
791     NaN           NaN                    NaN                    NaN   
792  2022.0         Papua       Kab. Biak Numfor               21847.63   
793  2022.0         Papua          Kota Jayapura                 940.00   
794     NaN           NaN                    NaN                    NaN   

     Luas RTH (km2)(B)  % RTH(B/A)  Taman Kota (km2)  Hutan Kota (km2)  \
0                  NaN         NaN               NaN               NaN   
1                  NaN         NaN               NaN               NaN   
2                  NaN         NaN               NaN               NaN   
3                  NaN         NaN               NaN               NaN   
4                  NaN         NaN               NaN               NaN   
..                 ...         ...               ...               ...   
790           15.34250       0.111              5.36              9.89   
791                NaN         NaN               NaN               NaN   
792          680.99590       3.117              0.02              7.60   
793            6.92567       0.737              0.04              6.09   
794                NaN         NaN               NaN               NaN   

     Jalur hijau di Jalan (km2)  Sempadan Sungai (km2)  Sempadan Pantai (km2)  \
0                           NaN                    NaN                    NaN   
1                           NaN                    NaN                    NaN   
2                           NaN                    NaN                    NaN   
3                           NaN                    NaN                    NaN   
4                           NaN                    NaN                    NaN   
..                          ...                    ...                    ...   
790                        0.07                   0.00                   0.02   
791                         NaN                    NaN                    NaN   
792                        0.88                 667.16                   2.23   
793                        0.05                   0.50                   0.16   
794                         NaN                    NaN                    NaN   

     Tempat Pemakaman Umum (km2)  Sempadan Rel Kereta Api (km2)  \
0                            NaN                            NaN   
1                            NaN                            NaN   
2                            NaN                            NaN   
3                            NaN                            NaN   
4                            NaN                            NaN   
..                           ...                            ...   
790                         0.00                            0.0   
791                          NaN                            NaN   
792                         0.03                            0.0   
793                         0.03                            0.0   
794                          NaN                            NaN   

     Jalur Hijau Jaringan Listrik Tegangan Tinggi (km2)  \
0                                                  NaN    
1                                                  NaN    
2                                                  NaN    
3                                                  NaN    
4                                                  NaN    
..                                                 ...    
790                      

#### **Merging**

In [ ]:
dataframe_1 = pd.DataFrame(
    [
        ['a', 1],
        ['b', 2]
    ],
    columns = ['huruf', 'angka']
)

dataframe_1

huruf  angka
0     a      1
1     b      2

In [ ]:
dataframe_2 = pd.DataFrame(
    [
        ['c', 3],
        ['d', 4]
    ],
    columns = ['huruf', 'angka']
)

dataframe_2

huruf  angka
0     c      3
1     d      4

In [ ]:
# axis = 0 = nambah kebawah / nambah breakaris
# axis = 1 = nambah kesampig / nambah kolom
pd.concat([dataframe_1, dataframe_2], axis = 0)

huruf  angka
0     a      1
1     b      2
0     c      3
1     d      4

## Numpy
berhubungan dengan array list
memberi dimensi ke array

In [ ]:
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [ ]:
mymatrix = [[1,2,3], [4,5,6]]
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# ingin membuat array 1 dimensi dalam nilai terurut dengan interval tertentu
# (0, 11, 2) :
# 0 : Angka mulainya
# 11 : Masimal index
# 2 : interval
newlist = np.arange(0, 11, 2)
newlist

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
# ingin membuat array 1 dimensi dalam nilai terurut dengan interval tertentu
# (0, 11) :
# 0 : Angka mulainya
# 11 : Masimal index
newlist_2 = np.arange(0, 11)
newlist_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# berdasarkan pembagian
# dari 0 sampai 100 dibagi menjadi 5 hasilnya.
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

Method Array lainnya:

[Lihat disini](https://linuxhint.com/use-python-numpy-zeros-ones-functions/)
\
[Random](https://www.w3schools.com/python/numpy/numpy_random.asp)

In [ ]:
from numpy import random
x = random.randint(100)
x

45

In [ ]:
# Memanipulasi array dimensi
matrix = np.array(mymatrix)
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Untuk transpose
matrix.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Broadcasting
# ingin memasukan nilai dari index ke 1 sampai 4 dengan nilai tertentu
newlist[1:4] = 100
newlist

array([  0, 100, 100, 100,   8,  10])

In [ ]:
myarr = np.array(mylist)
arrayplus = myarr + myarr
arrayplus

array([2, 4, 6])

In [ ]:
arraymult = myarr * myarr
arraymult

array([1, 4, 9])